- name: cdl_content
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
    - nembery.skillet

  tasks:
    # currently using clear text vars for testing
    - name: grab auth creds
      include_vars: 'vars.yml'
      no_log: 'yes'

    # check access to the system and pull a few values
    - name: show system info
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show system info'
      register: system_info
      until: system_info is not failed
      retries: 10
      delay: 10

    # json to dict to use in multiple places
    - set_fact: system_info_json="{{ system_info.stdout | from_json }}"

    # output software version for min version check
    - name: software version
      debug: msg='software version is {{ system_info_json.response.result.system['sw-version'] }}'

    # force quit to test part of playbook
    - set_fact: stop_playbook='stop'
    - name: stop playbook
      fail: msg="planned stop during testing"
      when: stop_playbook == 'stop'